// libs/react-ui/src/lib/track/track.tsx
import React, { FC, HTMLAttributes, PropsWithChildren } from 'react';

type TrackProps = HTMLAttributes<HTMLDivElement> & {
  gap?: number;
  align?: 'left' | 'center' | 'right' | 'stretch';
  justify?: 'start' | 'between' | 'center' | 'around' | 'end';
  layout?: 'flex' | 'grid';
  direction?: 'horizontal' | 'vertical';
  reverse?: boolean;
  isMultiline?: boolean;
};

const alignMap = {
  left: 'flex-start',
  center: 'center',
  right: 'flex-end',
  stretch: 'stretch',
};

const justifyMap = {
  start: 'flex-start',
  between: 'space-between',
  center: 'center',
  around: 'space-around',
  end: 'flex-end',
};

const TrackComponent: FC<PropsWithChildren<TrackProps>> = ({
  gap = 0,
  align = 'center',
  justify = 'start',
  direction = 'horizontal',
  layout = 'flex',
  isMultiline = false,
  reverse = false,
  children,
  style,
  ...rest
}) => {
  return (
    <div
      className="track"
      style={{
        display: layout,
        gap,
        alignItems: alignMap[align],
        justifyContent: justifyMap[justify],
        flexDirection:
          direction === 'horizontal'
            ? reverse
              ? 'row-reverse'
              : 'row'
            : reverse
            ? 'column-reverse'
            : 'column',
        flexWrap: isMultiline ? 'wrap' : undefined,
        ...style,
      }}
      {...rest}
    >
      {children}
    </div>
  );
};

export default TrackComponent;

// libs/ui/src/lib/track/track.component.ts
import { Component, HostBinding, Input } from '@angular/core';
import { Gap } from './track';

@Component({
  selector: 'veera-ng-track',
  templateUrl: './track.component.html',
})
export class TrackComponent {
  /** Gap in multiples of --veera-spacing-unit */
  @HostBinding('style.--gap')
  @Input()
  gap: Gap = 0;

  /** Equivalent of justify-content in CSS */
  @HostBinding('style.--horizontal-alignment')
  get getHostHorizontalAlignment(): string {
    return `
      ${this.horizontalAlignment === 'right' ? 'flex-end' : ''}
      ${this.horizontalAlignment === 'center' ? 'center' : ''}
    `;
  }
  @Input() horizontalAlignment: 'left' | 'center' | 'right' = 'left';

  /** Equivalent of flex-direction in CSS */
  @HostBinding('style.--direction') get getHostDirection(): string {
    return this.direction === 'horizontal' ? 'row' : 'column';
  }
  @Input() direction: 'horizontal' | 'vertical' = 'horizontal';

  /** Equivalent of flex-wrap in CSS */
  @HostBinding('style.--wrap') get getHostIsMultiline(): string {
    return this.isMultiline ? 'wrap' : '';
  }
  @Input() isMultiline = false;

  @HostBinding('class') get getHostClasses(): string {
    return `veera-track`;
  }
}
