// libs/ui/src/lib/table-of-contents/table-of-contents/table-of-contents.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  HostBinding,
  Input,
} from '@angular/core';

@Component({
  selector: 'cvi-ng-table-of-contents',
  templateUrl: './table-of-contents.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TableOfContentsComponent {
  @HostBinding('attr.aria-label') @Input() title!: string | null;

  @HostBinding('attr.role') roleAttr = 'navigation';
  @HostBinding('class') get getHostClasses(): string {
    return `cvi-table-of-contents__aside-inner`;
  }
  @HostBinding('attr.title') get getTitle(): null {
    return null;
  }
}

<h2 *ngIf="title" class="veera-table-of-contents__aside-title">{{ title }}</h2>
<div class="veera-table-of-contents__aside-list" role="list">
  <ng-content></ng-content>
</div>

// libs/react-ui/src/lib/table-of-contents/table-of-contents.tsx
import React, { PropsWithChildren } from "react";

type TableOfContentsProps = {
  readonly title: string;
}

const TableOfContentsComponent: React.FC<PropsWithChildren<TableOfContentsProps>> = (props) => {
  const { title, children } = props;

  return <div className="cvi-table-of-contents__aside">
    <div className="cvi-table-of-contents__aside-stickable">
      <div
        role="navigation"
        aria-label={title}
        className="cvi-table-of-contents__aside-inner"
      >
        <h2 className="cvi-table-of-contents__aside-title">{title}</h2>
        <ul className="cvi-table-of-contents__aside-list">
          {children}
        </ul>
      </div>
    </div>
  </div>;
}

export default TableOfContentsComponent;
