// libs/react-ui/src/lib/content-panel/content-panel.tsx
import React, { FC, PropsWithChildren } from 'react';

type ContentPanelProps = {
  title?: string;
};

const ContentPanelComponent: FC<PropsWithChildren<ContentPanelProps>> = ({
  title,
  children,
}) => {
  return (
    <div className="cvi-content-panel">
      <h1 className="cvi-content-panel__title">{title}</h1>
      {children}
    </div>
  );
};

export default ContentPanelComponent;

// libs/ui/src/lib/content-panel/content-panel.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  HostBinding,
  Input,
} from '@angular/core';

@Component({
  selector: 'cvi-ng-content-panel',
  templateUrl: './content-panel.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ContentPanelComponent {
  @Input() title = '';
  @HostBinding('class') get getHostClasses(): string {
    return `cvi-content-panel`;
  }
}

<h2 *ngIf="title" class="cvi-content-panel__title">{{ title }}</h2>
<ng-content></ng-content>
