// libs/react-ui/src/lib/table-of-contents/table-of-contents-wrapper/table-of-contents-wrapper.tsx
import React, { PropsWithChildren } from "react";

type TableOfContentWrapperProps = {
  readonly hideNavOnMobile?: boolean;
}

const TableOfContentsWrapperComponent: React.FC<PropsWithChildren<TableOfContentWrapperProps>> = (props) => {
  const { children, hideNavOnMobile = true } = props;
  return <div
      className={`cvi-table-of-contents ${hideNavOnMobile ? 'is-nav-hidden-on-mobile' : ''}`}
    >
      {children}
    </div>;
}

export default TableOfContentsWrapperComponent;

// libs/ui/src/lib/table-of-contents/table-of-contents-wrapper/table-of-contents-wrapper.component.ts
import { Component, HostBinding, Input } from '@angular/core';

@Component({
  selector: 'cvi-ng-table-of-contents-wrapper',
  templateUrl: './table-of-contents-wrapper.component.html',
})
export class TableOfContentsWrapperComponent {
  @Input() hideNavOnMobile = true;
  @HostBinding('class') get getHostClasses(): string {
    return `cvi-table-of-contents${
      this.hideNavOnMobile ? ' is-nav-hidden-on-mobile' : ''
    }`;
  }
}

<ng-content></ng-content>
<div class="cvi-table-of-contents__aside">
  <div class="cvi-table-of-contents__aside-stickable">
    <ng-content select="cvi-ng-table-of-contents"></ng-content>
  </div>
</div>
