// libs/react-ui/src/lib/form-item/form-item.tsx
import React, { forwardRef } from 'react';

type FormItemProps = {
  htmlId?: string;
  label?: string;
  placeholder?: string;
  labelPosition?: 'top' | 'side';
  isLabelHidden?: boolean;
  required?: boolean;
  disabled?: boolean;
};

const FormItem = forwardRef<HTMLInputElement, FormItemProps>(
  (
    {
      htmlId,
      label,
      placeholder,
      labelPosition = 'side',
      isLabelHidden = false,
      required = false,
      disabled = false,
      ...rest
    },
    ref
  ) => {
    return (
      <div
        className={`cvi-form-item cvi-form-item--label-position-${labelPosition}${
          required ? ' cvi-form-item--is-required' : ''
        }`}
      >
        {isLabelHidden === false && (
          <label htmlFor={htmlId} className="cvi-form-item__label">
            {`${label}${required ? ' *' : ''}`}
          </label>
        )}
        <input
          className="cvi-textfield__text-control"
          type="text"
          placeholder={placeholder ?? ''}
          disabled={disabled}
          id={htmlId}
          ref={ref}
          {...rest}
        />
      </div>
    );
  }
);

export default FormItem;

// libs/ui/src/lib/form-item/form-item.component.ts
import { Component, HostBinding, Input } from '@angular/core';

@Component({
  selector: 'cvi-ng-form-item',
  templateUrl: './form-item.component.html',
})
export class FormItemComponent {
  /** HTML id passed down to form field component */
  @Input() htmlId!: string;

  /** HTML label */
  @Input() label!: string;

  /** Label position */
  @Input() labelPosition: 'top' | 'side' = 'top';

  /** Label is visually hidden */
  @Input() isLabelHidden = false;

  /** Label is visually hidden */
  @Input() required = false;

  @HostBinding('class') get getHostClasses(): string {
    return `cvi-form-item cvi-form-item--label-position-${
      this.labelPosition
    }${this.required ? ' cvi-form-item--is-required' : ''}`;
  }
}

<label [ngClass]="{'cvi-form-item__label': !isLabelHidden, 'cvi-screenreader-text': isLabelHidden}" [attr.for]="htmlId">{{ label }}{{ required ? ' *' : ''}}</label>
<ng-content></ng-content>
